name: Build and Push Docker Image for MCPO

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io 
  IMAGE_NAME: fl0w1nd/mcpo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      packages: write 

    steps:
      - name: Checkout MCPO repository
        uses: actions/checkout@v4
        with:
          repository: open-webui/mcpo
          token: ${{ secrets.ACCESS_TOKEN }}
          path: mcpo-source

      - name: Get latest release tag
        id: get_version
        run: |
          cd mcpo-source
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "version=${LATEST_TAG}" >> $GITHUB_OUTPUT
          echo "Latest release tag: ${LATEST_TAG}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mcpo-source
          file: ./mcpo-source/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
